name: Docker Componse 

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image With Docker Componse 
      #run: docker-c build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker-compose up -d --build
